### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by jakzal** [jakzal/BehatRestExtension#5]
- [x] Allow http client injection into contexts (#4)
- [x] Provide Guzzle support
- [ ] Provide Symfony support
- [x] Provide Buzz support (#7)
- [ ] ~~Provide Simple cache support~~
- [x] Allow http client configuration via behat.yml (#6)
- [ ] ~~Provide a RestContext with a basic set of steps~~
- [ ] Provide a Debug listener printing out requests and responses after a failed step (#8)
- [ ] Provide support for response matchers with default https://github.com/coduo/php-matcher implementation
- [ ] Support several [httplug plugins](http://docs.php-http.org/en/latest/plugins/index.html) (#12)

**Comment by aRn0D** [comment]
@jakzal yes it sounds good to me!

**Comment by dunglas** [comment]
@jakzal pretty cool!

I'm looking for a tool to distribute in API Platform (https://github.com/dunglas/api-platform)

The more important for me is:
- Provide Symfony support (can be done with the PSR-7 bridge: support only PSR-7 internally will provide compatibility with Guzzle, ZF 3 and Symfony out of the box)
- Provide a RestContext with a basic set of steps (can help on that one)
- Provide support for response matchers with default

If you're interested in, I'll also be pleased to provide:
- JSON-LD support (maybe php-matcher will be sufficient)
- JWT authentication support

**Comment by jakzal** [comment]
Thanks for feedback! Most of these things already existed in the proof of concept, or other projects I've worked on, so it should be easy to port them over. I'll always start with a feature description, so that you guys can either give feedback, or help writing code.

JSON-LD and JWT sound like something for >1.0 release :)

**Comment by xabbuh** [comment]
What about relying on [egeloen/http-adapter](https://github.com/egeloen/ivory-http-adapter) if you want to provide support for both Guzzle and Buzz?

**Comment by theofidry** [comment]
Also interested in, great initiative! Can't wait for a true API context !!

**Comment by jakzal** [comment]
@xabbuh didn't know that one. Thanks! I'll have a look.

**Comment by jakzal** [comment]
@xabbuh I think the egeloen/http-adapter project is not stable yet. I'll reconsider when it matures.

**Comment by theofidry** [comment]
@jakzal any release date in mind?

**Comment by jakzal** [comment]
@theofidry yes. End of October/beginning of November.

**Comment by jakzal** [comment]
Unfortunately this is moving towards end of the year :/

**Comment by theofidry** [comment]
Fortunately the same goes for me ;)

**Comment by xabbuh** [comment]
@jakzal egeloen/http-adapter is no released with 1.0. But as it is deprecated I suggest to wait until [php-http/httplug](https://github.com/php-http/httplug/) is released.

**Comment by jakzal** [comment]
@xabbuh I have developed something similar :) obviously it's better if I can avoid maintaining it myself. Thanks for the link!

**Comment by xabbuh** [comment]
@jakzal Too bad, I should have told you about that project earlier but then forgot about it.

**Comment by xabbuh** [comment]
Just FYI, version 1.0.0 of php-http/httplug [has been released](https://github.com/php-http/httplug/releases/tag/v1.0.0).

**Comment by jakzal** [comment]
@xabbuh nice! I can revisit this extension now :)
